translations = {
    "de" : {
       "start_server"    : "Server starten",
       "stop_server"     : "Server stoppen",
       "stopping_msg"    : "server wird in 3 sekunden gestoppt!",
       "get_players"     : "Spieler anzeigen",
       "ban_player"      : "Spieler bannen",
       "unban_player"    : "Spieler entbannen",
       "kick_player"     : "Spieler kicken",
       "get_whitelist"   : "whitelist anzeigen",
       "player_info"     : "Spieler info",
       "create_backup"   : "Backup erstellen",
       "load_backup"     : "Backup laden",
       "server_info"     : "Server info",
       "continur_menu"   : "Drücke enter um fortzufahren...",
       "already_running" : "Server läuft bereits!",
       "not_running"     : "Server ist nicht gestartet!",
       "error"           : "Fehler",
       "server_starting" : "Server wird gestartet...",
       "server_stoping"  : "Server wird gestoppt...",
       "succes_stop"     : "Server erfolgreich gestoppt.",
       "error_stop"      : "Fehler beim stopen des servers",
       "backup_creating" : "Backup erstellen...",
       "backup_succes"   : "Backup erfolgreich erstellt!",
       "load_succes"     : "Backup erfolgreich geladen!",
       "error_loading"   : "Fehler beim laden des Backups",
       "error_backup"    : "Fehler beim erstellen des backups",
       "backup_file_err" : "Backup-Datei nicht gefunden!",
       "backup_load_1"   : "Backup vom",
       "backup_load_2"   : "wird geladen...",
       "backup_not_found": "Keine backups gefunden!",
       "db_conn_error"   : "Datenbank-Verbindung nicht verfügbar.",
       "error_playtime"  : "Keine Zeit für den Angegebenen spieler!",
       "re_parse_error"  : "Fehler beim Parsen",
       "json_error"      : "Daten nicht im erwarteten Format!",
       "not_found_1 "    : "Die Datei",
       "not_found_2"     : "wurde nicht gefunden...",
       "ssid_error"      : "WLAN SSID konnte nicht ermittelt werden",
       "server_status"   : "Server status",
       "wlan_ssid"       : "Wlan ssid",
       "local_server_ip" : "locale server IP",
       "bann_1"          : "Spieler",
       "bann_2"          : "wurde gebannt!",
       "unban_2"         : "wurde entbannt",
       "kick_2"          : "wurde gekickt!",
       "online_player"   : "Online Spieler",
       "playername"      : "Spielername",
       "banned_players"  : "Gebannte Spieler",
       "reason"          : "Grund (Optional):",
       "whitlist_players": "whitelist Spieler:",
       "no_in_whitelist" : "Keine Spieler in der whitelist.",
       "name"            : "name",
       "playtime"        : "Spielzeit",
       "status"          : "status",
       "position"        : "position",
       "invalid_player"  : "Ungültiger Spieler!",
       "backup_file"     : "Backup Datei",
    },
    "en" : {
       "start_server"    : "Start server",
       "stop_server"     : "Stop server",
       "stopping_msg"    : "server will stop in 3 seconds!",
       "get_players"     : "Show players",
       "ban_player"      : "Ban player",
       "unban_player"    : "Unban player",
       "kick_player"     : "Kick player",
       "get_whitelist"   : "Show whitelist",
       "player_info"     : "Player info",
       "create_backup"   : "Create backup",
       "load_backup"     : "Load backup",
       "server_info"     : "Server info",
       "continur_menu"   : "Press enter to continue...",
       "already_running" : "Server is already running!",
       "not_running"     : "Server is not started!",
       "error"           : "Error:",
       "server_starting" : "Server is starting...",
       "server_stoping"  : "Server is stopping...",
       "succes_stop"     : "Server stopped successfully.",
       "error_stop"      : "Error stopping the server",
       "backup_creating" : "Creating backup...",
       "backup_succes"   : "Backup created successfully!",
       "load_succes"     : "Backup loaded successfully!",
       "error_loading"   : "Error loading backup:",
       "error_backup"    : "Error creating backup:",
       "backup_file_err" : "Backup file not found!",
       "backup_load_1"   : "Backup from",
       "backup_load_2"   : "is loading...",
       "backup_not_found": "No backups found!",
       "db_conn_error"   : "Database connection not available.",
       "error_playtime"  : "No time for the specified player!",
       "re_parse_error"  : "Parsing error",
       "json_error"      : "Data not in expected format!",
       "not_found_1 "    : "The file",
       "not_found_2"     : "was not found...",
       "ssid_error"      : "WIFI SSID could not be determined",
       "server_status"   : "Server status",
       "wlan_ssid"       : "WIFI SSID",
       "local_server_ip" : "Local server IP",
       "bann_1"          : "Player",
       "bann_2"          : "was banned!",
       "unban_2"         : "was unbanned",
       "kick_2"          : "was kicked!",
       "online_player"   : "Online players",
       "playername"      : "Player name",
       "banned_players"  : "Banned players",
       "reason"          : "Reason (Optional):",
       "whitlist_players": "Whitelist players:",
       "no_in_whitelist" : "No players in the whitelist.",
       "name"            : "name",
       "playtime"        : "Playtime",
       "status"          : "status",
       "position"        : "position",
       "invalid_player"  : "Invalid player!",
       "backup_file"     : "Backup file",
    },
    "es" : {
       "start_server"    : "Iniciar servidor",
       "stop_server"     : "Detener servidor",
       "stopping_msg"    : "¡el servidor se detendrá en 3 segundos!",
       "get_players"     : "Mostrar jugadores",
       "ban_player"      : "Banear jugador",
       "unban_player"    : "Desbanear jugador",
       "kick_player"     : "Echar jugador",
       "get_whitelist"   : "Mostrar lista blanca",
       "player_info"     : "Información del jugador",
       "create_backup"   : "Crear copia de seguridad",
       "load_backup"     : "Cargar copia de seguridad",
       "server_info"     : "Información del servidor",
       "continur_menu"   : "Presiona enter para continuar...",
       "already_running" : "¡El servidor ya está en ejecución!",
       "not_running"     : "¡El servidor no ha sido iniciado!",
       "error"           : "Error:",
       "server_starting" : "Iniciando el servidor...",
       "server_stoping"  : "Deteniendo el servidor...",
       "succes_stop"     : "Servidor detenido con éxito.",
       "error_stop"      : "Error al detener el servidor",
       "backup_creating" : "Creando copia de seguridad...",
       "backup_succes"   : "¡Copia de seguridad creada con éxito!",
       "load_succes"     : "¡Copia de seguridad cargada con éxito!",
       "error_loading"   : "Error al cargar la copia de seguridad:",
       "error_backup"    : "Error al crear la copia de seguridad:",
       "backup_file_err" : "¡Archivo de copia de seguridad no encontrado!",
       "backup_load_1"   : "Copia de seguridad de",
       "backup_load_2"   : "se está cargando...",
       "backup_not_found": "¡No se encontraron copias de seguridad!",
       "db_conn_error"   : "Conexión a la base de datos no disponible.",
       "error_playtime"  : "¡No hay tiempo para el jugador especificado!",
       "re_parse_error"  : "Error al analizar",
       "json_error"      : "¡Datos no en el formato esperado!",
       "not_found_1 "    : "El archivo",
       "not_found_2"     : "no se encontró...",
       "ssid_error"      : "No se pudo determinar la SSID de WIFI",
       "server_status"   : "Estado del servidor",
       "wlan_ssid"       : "SSID de WIFI",
       "local_server_ip" : "IP del servidor local",
       "bann_1"          : "Jugador",
       "bann_2"          : "¡fue baneado!",
       "unban_2"         : "¡fue desbaneado!",
       "kick_2"          : "¡fue echado!",
       "online_player"   : "Jugadores en línea",
       "playername"      : "Nombre del jugador",
       "banned_players"  : "Jugadores baneados",
       "reason"          : "Razón (Opcional):",
       "whitlist_players": "Jugadores en lista blanca:",
       "no_in_whitelist" : "No hay jugadores en la lista blanca.",
       "name"            : "nombre",
       "playtime"        : "Tiempo de juego",
       "status"          : "estado",
       "position"        : "posición",
       "invalid_player"  : "¡Jugador no válido!",
       "backup_file"     : "Archivo de copia de seguridad",
    },
    "ru" : {
       "start_server"    : "Запустить сервер",
       "stop_server"     : "Остановить сервер",
       "stopping_msg"    : "сервер остановится через 3 секунды!",
       "get_players"     : "Показать игроков",
       "ban_player"      : "Забанить игрока",
       "unban_player"    : "Разбанить игрока",
       "kick_player"     : "Кикнуть игрока",
       "get_whitelist"   : "Показать белый список",
       "player_info"     : "Информация об игроке",
       "create_backup"   : "Создать резервную копию",
       "load_backup"     : "Загрузить резервную копию",
       "server_info"     : "Информация о сервере",
       "continur_menu"   : "Нажмите enter, чтобы продолжить...",
       "already_running" : "Сервер уже запущен!",
       "not_running"     : "Сервер не запущен!",
       "error"           : "Ошибка:",
       "server_starting" : "Сервер запускается...",
       "server_stoping"  : "Сервер останавливается...",
       "succes_stop"     : "Сервер успешно остановлен.",
       "error_stop"      : "Ошибка при остановке сервера",
       "backup_creating" : "Создание резервной копии...",
       "backup_succes"   : "Резервная копия успешно создана!",
       "load_succes"     : "Резервная копия успешно загружена!",
       "error_loading"   : "Ошибка при загрузке резервной копии:",
       "error_backup"    : "Ошибка при создании резервной копии:",
       "backup_file_err" : "Файл резервной копии не найден!",
       "backup_load_1"   : "Резервная копия от",
       "backup_load_2"   : "загружается...",
       "backup_not_found": "Резервные копии не найдены!",
       "db_conn_error"   : "Соединение с базой данных недоступно.",
       "error_playtime"  : "Нет времени для указанного игрока!",
       "re_parse_error"  : "Ошибка разбора",
       "json_error"      : "Данные не в ожидаемом формате!",
       "not_found_1 "    : "Файл",
       "not_found_2"     : "не найден...",
       "ssid_error"      : "Не удалось определить SSID Wi-Fi",
       "server_status"   : "Статус сервера",
       "wlan_ssid"       : "SSID Wi-Fi",
       "local_server_ip" : "Локальный IP сервера",
       "bann_1"          : "Игрок",
       "bann_2"          : "забанен!",
       "unban_2"         : "разбанен",
       "kick_2"          : "выкинут!",
       "online_player"   : "Игроки онлайн",
       "playername"      : "Имя игрока",
       "banned_players"  : "Забаненные игроки",
       "reason"          : "Причина (необязательно):",
       "whitlist_players": "Игроки в белом списке:",
       "no_in_whitelist" : "В белом списке нет игроков.",
       "name"            : "имя",
       "playtime"        : "Время игры",
       "status"          : "статус",
       "position"        : "позиция",
       "invalid_player"  : "Неверный игрок!",
       "backup_file"     : "Файл резервной копии",
    }
}
